[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "crewai-html-extractor"
version = "0.2.0"
description = "Extractor/tablas + turismo (JSON-LD, listados) con CLI y crawler"
readme = "README.md"
requires-python = ">=3.9"
# Si usas requirements.txt, puedes no listar deps aquí. Si prefieres, añade:
# dependencies = ["pandas","lxml","beautifulsoup4","requests","python-dateutil","tenacity","pyarrow","requests-cache","extruct","json5"]

[tool.setuptools]
# Layout plano: el código está en la raíz
package-dir = {"" = "."}

[tool.setuptools.packages.find]
# 🔒 Solo empaqueta crewai_html_extractor*
include = ["crewai_html_extractor*"]
# 🚫 Excluye todo lo viejo/descargado/build
exclude = ["src*", "Descarga*", "build*", "dist*", "outputs*", "tests*", "notebooks*", "*egg-info*", "__pycache__*"]

[project.scripts]
crewai-extract = "crewai_html_extractor.demo_cli:main"
crewai-crawl   = "crewai_html_extractor.crawl_cli:main"
